# --- User Account
user/account:
    resource: "@ControllerBundle/Resources/config/User/Rutas/Account.yml"
    prefix:   /account/

# --- User Contact
user/contact:
    resource: "@ControllerBundle/Resources/config/User/Rutas/Contact.yml"
    prefix:   /contact/