## --- User Account Login
user/account/login:
    
  path:         /login
  defaults  :   { _controller: ControllerBundle:User/Account:login}
  methods: [POST,OPTIONS]

## --- User Account exist
user/account/exist:
    
  path:         /exist
  defaults  :   { _controller: ControllerBundle:User/Account:exist}
  methods: [POST,OPTIONS]

## --- User Account SendCode
user/account/sendcode:
    
  path:         /sendcode
  defaults  :   { _controller: ControllerBundle:User/Account:sendCode}
  methods: [POST,OPTIONS]

## --- User Account CheckCode
user/account/checkcode:
    
  path:         /checkcode
  defaults  :   { _controller: ControllerBundle:User/Account:checkCode}
  methods: [POST,OPTIONS]

## --- User Account Create
user/account/c:
    
  path:         /c
  defaults  :   { _controller: ControllerBundle:User/Account:create}
  methods: [POST,OPTIONS]

## --- User Account SendCodeUser
user/account/sendcodeuser:
    
  path:         /sendcodeuser
  defaults  :   { _controller: ControllerBundle:User/Account:sendCodeUser}
  methods: [POST,OPTIONS]

## --- User Account SetNewPassword
user/account/setnewpwd:

  path:         /setnewpwd
  defaults  :   { _controller: ControllerBundle:User/Account:setNewPassword}
  methods: [POST,OPTIONS]