# --- User
User:
    resource: "@ControllerBundle/Resources/config/User/User.yml"
    prefix:   /user/

sendsms:
  path:         /sendsms
  defaults  :   { _controller: ControllerBundle:User/Account:sendSms}
  methods: [GET,OPTIONS]
