# --- User
User:
    resource: "@ControllerBundle/Resources/config/User/User.yml"
    prefix:   /user/

sendsmsget:
  path:         /sendsms
  defaults  :   { _controller: ControllerBundle:User/Account:sendSmsGet}
  methods: [GET]

sendsmspost:
  path:         /sendsms
  defaults  :   { _controller: ControllerBundle:User/Account:sendSmsPost}
  methods: [POST]
