## --- MyAccount Contact List
myaccount/contact/l:

  path:         /l
  defaults  :   { _controller: ControllerBundle:MyAccount/Contact:list}
  methods: [GET,OPTIONS]

## --- MyAccount Contact Read
myaccount/contact/r:

  path:         /r/{id}
  defaults  :   { _controller: ControllerBundle:MyAccount/Contact:read, id:null}
  methods: [GET,OPTIONS]

## --- MyAccount Contact Create
myaccount/contact/c:

  path:         /c
  defaults  :   { _controller: ControllerBundle:MyAccount/Contact:create}
  methods: [POST,OPTIONS]

## --- MyAccount Contact Update
myaccount/contact/u:
    
  path:         /u/{id}
  defaults  :   { _controller: ControllerBundle:MyAccount/Contact:update, id:null}
  methods: [PUT,OPTIONS]

## --- MyAccount Contact Delete
myaccount/contact/d:
    
  path:         /d/{id}
  defaults  :   { _controller: ControllerBundle:MyAccount/Contact:delete, id:null}
  methods: [DELETE,OPTIONS]