# --- MyAccount Info Toking
myaccount/info/toking:
    
  path:         /toking
  defaults  :   { _controller: ControllerBundle:MyAccount/Info:toking}
  methods: [GET,OPTIONS]

# --- MyAccount Info SetLocation
myaccount/info/setlocation:
    
  path:         /setlocation
  defaults  :   { _controller: ControllerBundle:MyAccount/Info:setLocation}
  methods: [PATCH,OPTIONS]

# --- MyAccount Info SendAlert
myaccount/info/sendalert:
    
  path:         /sendalert
  defaults  :   { _controller: ControllerBundle:MyAccount/Info:sendAlert}
  methods: [POST,OPTIONS]